# Generated by Django 4.2.3 on 2023-07-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterGatherDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gatherer', models.CharField(max_length=60)),
                ('completion', models.BooleanField()),
            ],
        ),
    ]
