# Generated by Django 4.2.3 on 2023-07-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lunch', models.CharField(max_length=60)),
                ('dinner', models.CharField(max_length=60)),
            ],
        ),
    ]
